language: node_js
node_js:
    - "6"
addons:
    apt:
        packages:
            - sshpass
script: ./ci/build_and_deploy.sh
language: java
addons:
    apt:
        packages:
            - oracle-java8-installer